function [Date_ZM,Date_NEMO,Date_Jarkus_topo,Date_Jarkus_bathy,Vlugtenburg_lopen,Vlugtenburg_jetski] = nemo_read_crsurvdates(workbookFile,sheetName,startRow,endRow)
%nemo_read_crsurvdates Reads the .xls file crossref_surveydates,
%contains the dates the different surveys were performed. And couples these
%data.
%
%   [Date_ZM,Date_NEMO,Date_Jarkus_topo,Date_Jarkus_bathy,Vluchtenburg_lopen,Vluchtenburg_jetski]
%   = nemo_read_crsurvdates(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [Date_ZM,Date_NEMO,Date_Jarkus_topo,Date_Jarkus_bathy,Vluchtenburg_lopen,Vluchtenburg_jetski]
%   = nemo_read_crsurvdates(FILE,SHEET) reads from the specified worksheet.
%
%   [Date_ZM,Date_NEMO,Date_Jarkus_topo,Date_Jarkus_bathy,Vluchtenburg_lopen,Vluchtenburg_jetski]
%   = nemo_read_crsurvdates(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
%
% Example:
%   [Date_ZM,Date_NEMO,Date_Jarkus_topo,Date_Jarkus_bathy,Vluchtenburg_lopen,Vluchtenburg_jetski] = importfile('crossref_surveydates.xls','Blad1',3,43);
%
%   See also NEMO, XLSREAD.

% Auto-generated by MATLAB on 2017/10/20 11:55:36

%% Copyright notice
%   --------------------------------------------------------------------
%   Copyright (C) 2016-2021 TU Delft
%       Bart Roest
%
%       l.w.m.roest@tudelft.nl
%
%       Stevinweg 1
%       2628CN Delft
%
%   This library is free software: you can redistribute it and/or modify
%   it under the terms of the GNU General Public License as published by
%   the Free Software Foundation, either version 3 of the License, or
%   (at your option) any later version.
%
%   This library is distributed in the hope that it will be useful,
%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%   GNU General Public License for more details.
%
%   You should have received a copy of the GNU General Public License
%   along with this library.  If not, see <http://www.gnu.org/licenses/>.
%   --------------------------------------------------------------------

%% Version <http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html>

% $Id: $
% $Date: $
% $Author: $
% $Revision: $
% $HeadURL: $
% $Keywords: $
%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 3;
    endRow = 300;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:F%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6]);

%% Allocate imported array to column variable names
Date_ZM = cellVectors(:,1);
Date_NEMO = cellVectors(:,2);
Date_Jarkus_topo = cellVectors(:,3);
Date_Jarkus_bathy = cellVectors(:,4);
Vlugtenburg_lopen = cellVectors(:,5);
Vlugtenburg_jetski = cellVectors(:,6);

%% Remove empties
for n=1:length(Date_ZM); mask(n)=~isempty(Date_ZM{n}); end
Date_ZM=Date_ZM(mask);
Date_NEMO=Date_NEMO(mask);
Date_Jarkus_topo=Date_Jarkus_topo(mask);
Date_Jarkus_bathy=Date_Jarkus_bathy(mask);
Vlugtenburg_lopen=Vlugtenburg_lopen(mask);
Vlugtenburg_jetski=Vlugtenburg_jetski(mask);

